source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'iOS Example' do
#  pod 'SidePanel', :path => '../'
  pod 'SidePanel', :path => '../'

  target 'Tests' do
    inherit! :search_paths

    
  end
end

